language: php

services:
  # - memcached
  # - mongodb
  - mysql
  # - rabbitmq
  - redis

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sudo apt-get install -qq --force-yes beanstalkd
  - sudo beanstalkd -d -l 127.0.0.1 -p 11300
  - composer self-update
  - composer install
  - pear install --alldeps PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=psr2 src/
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - "composer require --dev satooshi/php-coveralls:dev-master && php vendor/bin/coveralls -v"
