language: php

services:
  # - memcached
  # - mongodb
  - mysql
  # - rabbitmq
  - redis-server

php:
  - 5.4
  - 5.5

env:
  global:
   - BEANSTALK_URL="beanstalk://127.0.0.1:11300?queue=default&timeout=1"
   - MEMORY_URL="memory:///?queue=default&timeout=1"
   - MYSQL_URL="mysql://travis@127.0.0.1:3306/$DATABASE_NAME?queue=default&timeout=1"
   - NULL_URL="null:///?queue=default&timeout=1"
   - REDIS_URL="redis://travis@127.0.0.1:6379/0?queue=default&timeout=1"
   - MEMORY_URL="synchronous:///?queue=default&timeout=1"

before_script:
  # beanstalkd
  - sudo apt-get install -qq --force-yes beanstalkd
  - sudo beanstalkd -d -l 127.0.0.1 -p 11300

  # mysql
  - mysql -e 'CREATE DATABASE database_name;'
  - mysql database_name < config/schema-mysql.sql

  # extensions
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  - composer self-update
  - composer install
  - pear install --alldeps PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=psr2 src/
  - phpunit
  - vendor/bin/phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode

after_success:
  - php vendor/bin/coveralls -v
